version: '3'

services:

  db:
    image: 'influxdb:latest'
    ports:
      - '8083:8083'
      - '8086:8086'
    environment:
      INFLUXDB_ADMIN_ENABLED: 'true'
    volumes:
      - './influxdb.conf:/etc/influxdb/influxdb.conf:ro'
    command: -config /etc/influxdb/influxdb.conf

  dashboard:
    image: 'grafana/grafana:latest'
    ports:
      - '3000:3000'
    links:
      - db

