version: '3'

services:

  db:
    image: 'influxdb:1.8.10'
    ports:
      - '8083:8083'
      - '8086:8086'
      - '8080:8080'
    environment:
      INFLUXDB_ADMIN_ENABLED: 'true'
    volumes:
      - './data/influxdb:/var/lib/influxdb'
      - './influxdb.conf:/etc/influxdb/influxdb.conf:ro'
    command: -config /etc/influxdb/influxdb.conf

  dashboard:
    image: 'grafana/grafana-oss:8.3.3'
    ports:
      - '3000:3000'
    links:
      - db

